Updated tool and readme

diff --git a/cmplasm b/cmplasm
--- a/cmplasm
+++ b/cmplasm
@@ -6,32 +6,38 @@ show_help() {
     echo "If you specify only the name of the program (without extension), it defaults to x86 format."
     echo ""
     echo "Syntax:"
-    echo "  cmplasm [name_without_extension] [output_name] -f [nasm_format]"
+    echo "  cmplasm [options] file_to_compile.asm"
     echo ""
     echo "Options:"
-    echo "  name_without_extension  The base name of your assembly file (without .asm)."
-    echo "  output_name             The desired name of the output executable."
-    echo "  -f nasm_format          Specifies the NASM format (e.g., elf32, elf64, win32, win64)."
+    echo "  -o output_name        The desired name of the output executable."
+    echo "  -f nasm_format        Specifies the NASM format (e.g., elf32, elf64, win32, win64)."
+    echo "  -g                    Compile with debug information for GDB."
+    echo "  -h, --help            Display this help message."
     echo ""
     echo "Examples:"
     echo "  cmplasm myprogram -f elf32"
-    echo "  cmplasm myprogram myoutput -f elf64"
+    echo "  cmplasm myprogram -o myoutput -f elf64 -g"
 }
 
 # Default values
 format="elf32"   # Default NASM format
 output_name=""
+debug=""
 
 # Parse arguments
 while [[ "$#" -gt 0 ]]; do
     case $1 in
+        -o) output_name="$2"; shift 2;;
         -f) format="$2"; shift 2;;
+        -g) debug="-g"; shift;;
         -h|--help) show_help; exit 0;;
         *) 
             if [[ -z "$input_name" ]]; then
                 input_name="$1"
             else
-                output_name="$1"
+                echo "Error: Unrecognized argument '$1'"
+                show_help
+                exit 1
             fi
             shift;;
     esac
@@ -58,7 +64,7 @@ if [[ -f "$output_name" ]]; then
 fi
 
 # Compile assembly file
-nasm -f "$format" "$input_name.asm"
+nasm -f "$format" $debug "$input_name.asm" -o "${input_name}.o"
 if [[ $? -ne 0 ]]; then
     echo "Error: NASM compilation failed."
     exit 1
